//
// Created by Alienson on 10.8.2024..
//

#ifndef RHYTHM_SPRITESTATES_H
#define RHYTHM_SPRITESTATES_H

enum CommonEntityStates{
    STATE_HURT, STATE_DEATH, STATE_COUNT
};

enum PlayerStates{
    PLAYER_PUNCH, PLAYER_WHIP, PLAYER_DEATH, PLAYER_JUMP, PLAYER_DOUBLE_JUMP, PLAYER_HURT, PLAYER_IDLE, PLAYER_KICK, PLAYER_RUN
};

#endif