set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_ENV_PASSTHROUGH PATH)
set(VCPKG_CMAKE_C_COMPILER "C:/Program Files/JetBrains/CLion 2025.1.1/bin/mingw/bin/gcc.exe")
set(VCPKG_CMAKE_CXX_COMPILER "C:/Program Files/JetBrains/CLion 2025.1.1/bin/mingw/bin/g++.exe")
set(VCPKG_CMAKE_SYSTEM_NAME MinGW)
set(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
